INSERT INTO SCHOOLS([sch_name],[sch_address],[sch_phone]) VALUES('Hayes Ryan','503-4968 Mauris Av.','0971918495');

INSERT INTO DEPARTMENTS([dep_name],[sch_id]) VALUES('Dieter Ortiz',1);
INSERT INTO DEPARTMENTS([dep_name],[sch_id]) VALUES('Blaze Collier',1);
INSERT INTO DEPARTMENTS([dep_name],[sch_id]) VALUES('Walker Chambers',1);
INSERT INTO DEPARTMENTS([dep_name],[sch_id]) VALUES('Keith Parrish',1);
INSERT INTO DEPARTMENTS([dep_name],[sch_id]) VALUES('Alec Leach',1);

INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Marcia Jordan',1);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Alma Mcclure',1);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Ria Hess',3);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Penelope Richard',2);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Angelica Haley',3);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Wesley Barlow',5);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Nathaniel Craft',3);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Jessamine Lambert',1);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('TaShya Langley',2);
INSERT INTO SUBJECT_GROUP([sg_name],[dep_id]) VALUES('Francis Fuentes',4);

INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('1','Xaviera','Mcneil','0350614213','P.O. Box 364, 3872 Tellus. Avenue','Maecenas@pellentesque.org','F','1997-07-14',1,'DWW12INY9BL', 1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('2','Bert','Rodriguez','0453588747','287-6533 Libero Road','posuere.cubilia.Curae@luctus.org','M','2000-03-12',1,'BUR24QWJ1LU',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('3','Hayden','Thornton','0444682685','P.O. Box 454, 4864 Rutrum Rd.','lobortis.Class@Suspendissedui.co.uk','F','1996-03-10',1,'PRA37ITN5OK',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('4','Barclay','Albert','0813401421','P.O. Box 891, 649 Egestas Rd.','dolor.sit.amet@eget.net','M','1998-12-06',1,'FSU35BHK5NX',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('5','Bell','Jensen','0796300870','Ap #890-7320 Duis Road','mi.pede.nonummy@turpis.com','M','1996-05-15',2,'YJL21QOV0PR',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('6','Xandra','Barnes','0391788028','P.O. Box 312, 7986 Ac Av.','ut.sem@mattis.co.uk','F','1996-09-20',2,'UMN87PMA9BF',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('7','Macy','Burke','0798895085','836-4566 Quam St.','Proin.velit.Sed@mollis.com','M','1999-11-29',1,'AOX35NKC8YR',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('8','Owen','Elliott','0681887545','P.O. Box 288, 887 Libero Road','Integer.in@afeugiat.co.uk','M','1996-04-22',2,'LAN79GJT5VN',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('9','Olympia','Chandler','0091212644','9927 Integer Street','Nunc@Aliquam.co.uk','M','1995-10-14',2,'SQX29PHZ6LN',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('10','Allistair','Andrews','0887776068','P.O. Box 974, 5686 Facilisis Rd.','ligula@Crasdictumultricies.net','F','2000-03-03',1,'EHB79GDV2NB',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('11','Zeus','Farmer','0633130244','270-6212 Ridiculus Avenue','commodo.ipsum.Suspendisse@porttitorerosnec.co.uk','F','1996-05-21',1,'HYH51SWX1DE',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('12','Cassady','Shaffer','0253904168','721-8007 Consectetuer St.','ligula.Aliquam@tincidunt.edu','F','1998-06-28',2,'WUR08XNE0MT',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('13','Grant','Glenn','0213406296','Ap #296-213 Ante, St.','Integer.id.magna@dolortempus.org','M','1997-10-26',2,'BEQ80ZSG6IC',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('14','Tiger','Rivas','0365616002','Ap #436-9498 Fermentum Rd.','Quisque.libero@rutrumurna.ca','M','1998-05-24',2,'NJK73IYJ5HM',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('15','Isabella','Burch','0679435981','Ap #157-4222 Ultrices Road','ut.mi@dapibusquam.edu','M','1998-06-10',2,'YDM67ZKM5XA',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('16','Yolanda','Hooper','0718379135','Ap #838-2808 Quis, Road','posuere.cubilia@vitaeorciPhasellus.net','F','1998-05-10',2,'RJV23BRG7OC',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('17','Danielle','Gonzalez','0123790259','Ap #638-7530 Magna. St.','Maecenas.iaculis.aliquet@odio.edu','F','2000-03-14',2,'ROW83GKZ2WZ',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('18','Reuben','Peterson','0962818140','1705 Enim. St.','semper.erat@Morbi.ca','M','1999-10-07',2,'YLX48CRB1YD',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('19','Karen','Hickman','0905910126','P.O. Box 508, 5230 Ac, Rd.','Integer.sem@utaliquamiaculis.co.uk','M','1996-10-14',1,'ZNQ12HWH1NX',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('20','Olga','Mccarthy','0461262474','Ap #234-8214 Quis Road','sem@Nullamenim.net','F','1999-01-13',2,'KPO12ITF6YR',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('21','Declan','Humphrey','0469377449','P.O. Box 732, 6877 Nascetur Av.','gravida.non.sollicitudin@quispede.co.uk','F','1997-02-22',1,'XXD81SRW6KE',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('22','Brent','Bartlett','0692115463','P.O. Box 568, 9526 Nisi St.','Cras.pellentesque.Sed@fringillapurusmauris.co.uk','M','1996-05-04',1,'PKZ68ZEJ2HG',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('23','Quinn','Coffey','0304710856','P.O. Box 751, 1531 Mattis Rd.','mi.Aliquam@hendrerit.com','F','1998-08-08',2,'SJN22MFB4QN',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('24','Cameron','Best','0082655612','Ap #187-7789 Id, Avenue','magna.Phasellus.dolor@elit.net','F','1999-08-17',2,'WSA59HCF3MQ',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('25','Ezra','Acosta','0167034550','559-9867 Aenean Street','laoreet.ipsum@quamquisdiam.ca','F','1996-06-21',2,'VAM63DWA9DA',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('26','Felicia','Dean','0070694914','P.O. Box 679, 9457 Iaculis, Ave','ac.nulla@estmollisnon.edu','F','1999-10-11',1,'UES96ZUS5ZI',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('27','Bo','Gonzalez','0191943580','5316 Elit. Road','odio.Etiam.ligula@Vestibulum.com','F','1999-02-04',2,'BHK11RCZ3JU',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('28','Avram','Delaney','0149475307','3921 Donec St.','sem.ut@metus.ca','M','1997-02-05',1,'CKO28QNZ9GP',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('29','Blake','Barr','0464144781','351-9828 Integer Avenue','vestibulum@urnaconvallis.org','F','1999-09-25',1,'DNT10OXD3DQ',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('30','Samuel','Meyer','0172425228','Ap #655-8460 Ut Road','mauris.ipsum@indolor.edu','M','1997-12-23',2,'OQA49MEM8JN',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('31','Cailin','Sutton','0939836572','230-6946 Velit. Road','justo.nec.ante@ornare.com','M','2000-02-18',2,'UCW95BUG3NO',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('32','Brock','Lowery','0356914556','P.O. Box 736, 5117 Turpis Street','Proin.vel@Aliquameratvolutpat.edu','F','2000-02-28',2,'OCX73PTB0ME',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('33','Wing','Zamora','0838136057','Ap #915-1903 Litora Av.','mauris.aliquam.eu@adlitoratorquent.com','M','2000-05-24',2,'UME73GBB3MI',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('34','Hakeem','Cameron','0523652708','Ap #817-173 Sed St.','Ut.tincidunt@atiaculisquis.co.uk','F','1999-10-02',2,'TUT07JID0KV',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('35','Maxwell','Johnson','0171961553','404-5424 Ac St.','fermentum.metus@imperdietullamcorperDuis.co.uk','M','1999-05-11',2,'DDT63LXG2BZ',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('36','Lois','Harmon','0742372912','P.O. Box 911, 6488 Velit. Rd.','dapibus.rutrum@Suspendissetristiqueneque.co.uk','F','1996-04-23',2,'NAB21KSU6BQ',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('37','Eric','Guthrie','0782343009','5222 Nunc Rd.','porta@mattisornare.com','F','1995-09-06',1,'LAE56EMS5CH',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('38','Lana','Morales','0785870394','2726 Eget, Ave','libero@tortor.ca','M','1998-09-12',2,'ESL48OHG7DK',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('39','Walter','Parsons','0938426467','987-5703 Vel Rd.','tellus@ligulaconsectetuerrhoncus.co.uk','F','1998-07-28',1,'MNZ47BOF6RF',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('40','Orlando','Montgomery','0241251321','P.O. Box 953, 917 Nibh. Av.','mattis.Cras.eget@intempuseu.com','F','1999-06-01',2,'ZAB68RLL4SJ',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('41','Candace','Norton','0378084677','P.O. Box 913, 7237 Nec Rd.','sociis@quamvelsapien.net','M','1997-10-18',1,'DJE61CSP7NR',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('42','Steel','Delaney','0458759295','Ap #915-8810 Mauris St.','massa.Quisque@Quisqueornare.co.uk','F','2000-04-15',1,'API99MWC1AI',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('43','Odysseus','Francis','0358026386','Ap #872-5788 Lectus Road','tristique.pellentesque@Vivamusnibh.ca','M','1996-07-02',2,'JHA99PKL0AK',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('44','Harrison','Woods','0138856896','P.O. Box 687, 5036 Nascetur St.','quis@tincidunt.ca','M','2000-07-12',1,'WNO85KPN7ZL',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('45','Mira','Abbott','0750249575','8721 Integer Street','auctor.nunc.nulla@venenatisa.org','F','1996-04-06',1,'CZI30ICN9VK',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('46','Ahmed','Jensen','0760472841','7094 Scelerisque Road','enim@idnuncinterdum.co.uk','F','1996-08-10',1,'LPP78ION9WL',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('47','Noel','Stone','0355523199','681-4612 Metus Rd.','non.egestas@sitametornare.edu','F','1997-12-16',2,'HZV18GTL8KS',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('48','Kaseem','Huber','0510559128','P.O. Box 708, 952 Id, Avenue','odio.Nam.interdum@enim.co.uk','F','2000-01-10',1,'SWX96FDI5EU',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('49','Courtney','Morrison','0932381982','P.O. Box 661, 7047 Morbi Road','nibh@facilisis.ca','M','2000-08-20',1,'XMF72YEM2SN',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password],[dep_id]) VALUES('50','Jana','Coleman','0109930847','P.O. Box 300, 7129 Non St.','nec@aceleifend.net','F','1997-07-27',2,'BOK65TRS7GJ',1);
INSERT INTO ACCOUNTS([acc_id],[acc_firstname],[acc_lastname],[acc_phone],[acc_address],[acc_email],[acc_gender],[acc_birthdate],[acc_type],[acc_password]) VALUES('admin','tien dat','Ung','0905142539','104 Binh Quoi','tiendat@gmail.com','M','2000-08-23',3,'123');

INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Kareem Monroe','2021-11-02','16',1,'2022-11-02','T2-4-6 15h30','E01');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Malachi Anderson','2021-10-03','18',1,'2022-10-03','T2-4-6 15h30','E02');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Morgan Sparks','2021-11-24','17',1,'2022-11-24','T2-4-6 15h30','E03');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Laith Combs','2021-11-13','16',1,'2022-11-13','T2-4-6 15h30','E04');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Rhoda Sullivan','2021-10-29','14',2,'2022-10-29','T2-4-6 7h00','E01');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Sigourney Alford','2021-10-25','15',2,'2022-10-25','T2-4-6 7h00','E02');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Kimberley Mclean','2021-09-17','17',2,'2022-09-17','T2-4-6 7h00','E03');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Zia Green','2021-08-20','13',2,'2022-08-20','T2-4-6 7h00','E04');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Hadley Sutton','2021-09-20','15',3,'2022-09-20','T3-5-7 7h00','E01');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Joshua Henry','2021-10-25','16',3,'2022-10-25','T3-5-7 7h00','E02');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Erica Gould','2021-06-25','15',3,'2022-06-25','T3-5-7 7h00','E03');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Caryn Pate','2021-09-03','15',3,'2022-09-03','T3-5-7 7h00','E04');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Jin Schultz','2021-10-20','17',4,'2022-10-20','T3-5-7 15h30','E01');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Risa Wiley','2021-07-22','13',4,'2022-07-22','T3-5-7 15h30','E02');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Cody Garza','2021-10-22','16',4,'2022-10-22','T3-5-7 15h30','E03');
INSERT INTO SUBJECTS([sub_name],[sub_startdate],[tea_id],[sg_id],[sub_enddate],[sub_schedule],[sub_room]) VALUES('Walter Fischer','2021-10-05','18',4,'2022-10-05','T3-5-7 15h30','E04');

INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('42',1);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('41',1);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('41',2);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('41',3);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('42',2);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('41',4);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('42',3);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('42',4);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('41',5);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('42',5);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('45',1);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('45',2);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('44',1);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('46',1);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('45',3);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('46',2);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('46',3);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('44',2);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('46',4);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('46',5);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('46',6);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('44',3);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('45',4);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('44',4);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('45',5);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('45',6);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('44',5);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('44',6);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('44',7);
INSERT INTO STU_SUBJECT([stu_id],[sub_id]) VALUES('46',7);

select * from ACCOUNTS where acc_type = 2 order by acc_id
select * from SUBJECTS where sub_id = 12;
select * from POINTS