
CREATE DATABASE QLSV;
GO

USE QLSV;

CREATE TABLE SCHOOLS (
	sch_id INT IDENTITY(1,1) PRIMARY KEY,
	sch_name VARCHAR(100),
	sch_address VARCHAR(100),
	sch_phone VARCHAR(10)
);


CREATE TABLE DEPARTMENTS (
	dep_id INT IDENTITY(1,1) PRIMARY KEY,
	dep_name VARCHAR(100),
	sch_id INT
);

CREATE TABLE SUBJECT_GROUP (
	sg_id INT IDENTITY(1,1) PRIMARY KEY,
	sg_name VARCHAR(100),
	dep_id INT
);


CREATE TABLE SUBJECTS (
	sub_id INT IDENTITY(1,1) PRIMARY KEY,
	sub_name VARCHAR(100),
	sub_startdate DATE,
	sub_enddate DATE,
	sub_schedule VARCHAR(100),
	sub_room VARCHAR(50),
	tea_id VARCHAR(8),
	sg_id INT
);


CREATE TABLE STU_SUBJECT (
	stu_id VARCHAR(8) NOT NULL,
	sub_id INT NOT NULL,
	p_midterm FLOAT,
	p_endterm FLOAT,
	PRIMARY KEY (stu_id, sub_id)
);

CREATE TABLE ACCOUNTS (
	acc_id VARCHAR(8) PRIMARY KEY,
	acc_avatar VARCHAR(50),
	acc_firstname VARCHAR(50),
	acc_lastname VARCHAR(50),
	acc_phone VARCHAR(10),
	acc_address VARCHAR(100),
	acc_email VARCHAR(50),
	acc_gender CHAR(1),
	acc_birthdate DATE,
	dep_id INT,
	acc_type INT,
	acc_password VARCHAR(50)
);

ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (sch_id) REFERENCES SCHOOLS(sch_id);

ALTER TABLE SUBJECT_GROUP ADD FOREIGN KEY (dep_id) REFERENCES DEPARTMENTS(dep_id);
ALTER TABLE ACCOUNTS ADD FOREIGN KEY (dep_id) REFERENCES DEPARTMENTS(dep_id);

ALTER TABLE SUBJECTS ADD FOREIGN KEY (sg_id) REFERENCES SUBJECT_GROUP(sg_id);
ALTER TABLE SUBJECTS ADD FOREIGN KEY (tea_id) REFERENCES ACCOUNTS(acc_id);

ALTER TABLE STU_SUBJECT ADD FOREIGN KEY (stu_id) REFERENCES ACCOUNTS(acc_id);
ALTER TABLE STU_SUBJECT ADD FOREIGN KEY (sub_id) REFERENCES SUBJECTS(sub_id);

